### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kimuraakiia** [lakshh07/Web3-Starter-Kit#2]
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

**Comment by lakshh07** [comment]
@kimuraakiia Thanks for reaching out! I have fixed the issue. 👍🏻

**Comment by kimuraakiia** [comment]
> @kimuraakiia Thanks for reaching out! I have fixed the issue. 👍🏻

how did you solve this bug?
